name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - uses: zhulik/redis-action@v1.1.0
      with:
        redis version: '5'
        number of databases: 100
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Run tests
      run: dotnet test --configuration Release
